yarnPath: .yarn/releases/yarn-4.3.1.cjs
enableGlobalCache: false
supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - musl
    - current
    - glibc
  os:
    - darwin
    - linux
