enableGlobalCache: false

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - musl
    - current
    - glibc
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.5.0.cjs
